import { cn } from "@/lib/utils"
import "@/styles/globals.css"
import type { Metadata } from "next"
import { Poppins, Quicksand } from "next/font/google"
import { Footer } from "./_/footer"
import { Header } from "./_/header"

// FONTS ***********************************************************************************************************************************
const poppins = Poppins({weight: "700", subsets: ["latin"], variable: "--font-heading"})
const quicksand = Quicksand({subsets: ["latin"], variable: "--font-base"})

// METADATA ********************************************************************************************************************************
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="fr">
      <body
        className={cn(
          "font-base flex min-h-screen flex-col overflow-x-hidden overflow-y-scroll antialiased",
          poppins.variable,
          quicksand.variable
        )}
      >
        <Header className="sticky top-0 z-20" />
        {children}
        <Footer />
      </body>
    </html>
  )
}

// TYPES ***********************************************************************************************************************************
export type RootLayoutProps = {children: React.ReactNode}
